---
# 파티션도 새로 만들고, filesystem도 새로 만듬
makePart: false
# makePart가 true이면 반드시 lun을 list로 넘겨줘야 함
luns: ['0','1']
# data disk를 mount 해야하는 지 아닌 지
mountDisk : false
# mkfs를 돌려야 하는 지?
mkfs: false
fstype: xfs

logpath:  /mnt/resource/log
datapath: /mnt/resource/data
binding_port: 27017
mongouser: mongod

selinuxmode : false

startMongoShard: false
#setup mongo replica
# mongod.conf.j2에서는 왜 여기에 선언된 variable은 인지를 못하지? defaults에 있는 것은 인지함
#setupreplica: true
#replsetName: MyReplicaSet