---
- hosts: mongo_mongos
  roles:
  - common
  tasks:
  - name: run mongo_common tasks
    include_role: 
      name: mongo_common
    vars:
      makePart: false
      luns: []
      mountDisk : false
      mkfs: false
      fstype: xfs
      logpath:  /mnt/resource/log
      datapath: /mnt/resource/data
      binding_port: 27017
      mongouser: mongod
      selinuxmode : false
    tags: mongo_common
  - name: run mongo_mongos tasks
    include_role: 
      name: mongo_mongos
    vars:
      startMongoMongos: true
      mongouser: mongod
      logpath:  /mnt/resource/log
      binding_port: 27017
      configServerList: MyConfigRepl/minschoconfig01:27017
    tags: mongo_mongos